### ISSUE TITLE
Logging configuration fails with a TypeError

### ISSUE THREAD

**Issue by Diapolo10** [mharrisb1/logging518#16]
I'm trying to use this in a project using Python 3.10 on Ubuntu 22.04 LTS (via WSL2), but as the title says I keep getting a `KeyError` - it seems that whatever this package does to inject the config to `logging` must've gotten outdated somehow.

Long story short, if I attempt to run the following code snippet

```py
import logging

import logging518.config

from my_config import PYPROJECT_TOML  # pathlib.Path object pointing to the file

logging518.config.fileConfig(PYPROJECT_TOML)
logger = logging.get_logger(__name__)


def main() -> None:
    logger.info("Logging works!")


if __name__ == '__main__':
    main()
```

I get the following response:

```sh
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.10/logging/config.py", line 746, in configure_handler
    result = factory(**kwargs)
TypeError: FileHandler.__init__() got an unexpected keyword argument 'file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/johntitor/stuff/panik-core/src/panik/main.py", line 7, in <module>
    logging518.config.fileConfig("pyproject.toml")
  File "/home/johntitor/.cache/pypoetry/virtualenvs/panik-core-fdSvtqVj-py3.10/lib/python3.10/site-packages/logging518/config.py", line 48, in fileConfig
    logging.config.dictConfig(tool_table_logging)
  File "/usr/lib/python3.10/logging/config.py", line 811, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.10/logging/config.py", line 572, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'filehandler'
```

I think this is a bug and not user error, but I'd be happy to be proven wrong.

**Comment by mharrisb1** [comment]
Hey @Diapolo10 thanks for creating the issue. Are you comfortable sharing the values in `PYPROJECT_TOML`? Specifically just anything under the logging tool table `[tool.logging]` and I'll try to reproduce

**Comment by Diapolo10** [comment]
Certainly, I'll provide the entire file excluding irrelevant things (like linter config), and I'll do some name-mangling since this is a work project.

```toml
[build-system]
requires = ['poetry-core>=1.2.0', 'wheel',]
build-backend = 'poetry.core.masonry.api'


[tool.logging]
version = 1

[tool.logging.formatters.formatter]
class = 'logging.Formatter'
format = '%(asctime)s [%(levelname)-7s] logger=%(name)s L%(lineno)-4d %(funcName)s() %(message)s'

[tool.logging.handlers.filehandler]
level = 'DEBUG'
class = 'logging.FileHandler'
file = 'alerter.log'
formatter = 'formatter'

[tool.logging.handlers.consolehandler]
level = 'ERROR'
class = 'logging.StreamHandler'
formatter = 'formatter'

[tool.logging.alerter]
level = 'DEBUG'
handlers = ['filehandler', 'consolehandler']

[tool.logging.alerter.auxiliary]
propagate = false

[tool.logging.alerter.auxiliary.Auxiliary]
propagate = false


[tool.poetry]
name = 'panik-core'
version = '0.1.0'
description = "Thingymabob"

packages = [
    { include = 'panik', from = 'src' },
    { include = 'panik_core', from = 'src' },
    { include = 'panik_database', from = 'src' },
]

authors = ["Lorem Ipsum <lorem.ipsum@dolorsita.net>",]

include = ['CHANGELOG.md', 'pyproject.toml', 'py.typed',]
license = 'Proprietary'
readme = 'README.md'

keywords = [
    'python3',
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: Implementation :: CPython',
    'Programming Language :: Python :: Implementation :: PyPy',
    'Typing :: Typed',
]

[tool.poetry.dependencies]
python = '^3.8.1'
logging518 = '^1.0.0'
python-dotenv = '^1.0.0'
typing-extensions = { version = '^4.7.1', python = '<3.11' }

[tool.poetry.group.dev.dependencies]
mypy = '^1.5.1'

[tool.poetry.group.linters]
optional = true

[tool.poetry.group.linters.dependencies]
ruff = '^0.0.285'

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = '^7.4.0'
pytest-cov = '^4.1.0'
```

The logging config is largely based on a mix of [one of my personal projects](https://github.com/Diapolo10/5G00EV25-3001_server/blob/main/logging.conf) and the `logging518` cookbook.
